name: Build .NET 4.8

on:
  push:
  pull_request:
    branches: [ master, main, develop/* ]
    paths:
    - '**.cs'
    - '**.csproj'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-net9:
    name: build-net48-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [windows-latest]    
        include:
          - framework: 'net48'
            dotnet-version: '4.8.x'
            configuration: 'Release'
            customtesttarget: net48
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build OpcDaAeHdaClientSolution.sln
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "OpcDaAeHdaClientSolution.sln"
